export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_USERCONTROL = "TOGGLE_USERCONTROL";
export const LOGIN_STATE = "LOGIN_STATE";
export const ACTIVE_MENU = "ACTIVE_MENU";

export const TOGGLE_DIALOG = "TOGGLE_DIALOG";